import { Bank, Guide, DebitCard, Transaction, TransactionType } from './types';

export const INITIAL_BANKS: Bank[] = [
    { id: '1', name: 'BAJIO CLASICA' },
    { id: '2', name: 'PYPSA BBVA' },
    { id: '3', name: 'PYPSA USD' },
    { id: '4', name: 'MESA DE DINERO' },
    { id: '5', name: 'MAESTRA' },
    { id: '6', name: 'PYPSA EURO' },
    { id: '7', name: 'PYP BBVA' },
    { id: '8', name: 'PYPSA GEO' },
    { id: '9', name: 'PYPSA 302' },
    { id: '10', name: 'PYP USD' },
    { id: '11', name: 'BAJIO PRESTAMO' },
];

export const INITIAL_GUIDES: Guide[] = [
  { id: '0', name: '0-Saldo Inicial' },
  { id: '1', name: '1-P0510 - [GCI] Refinería de Tula, Paquete 4. Fase II' },
  { id: '2', name: '2-P0507 - [PEP] Instalaciones Marinas PEP' },
  { id: '3', name: '3-MEPI' },
  { id: '4', name: '4-IDINSA' },
  { id: '5', name: '5-PERU' },
  { id: '6', name: '6-OTROS' },
  { id: '7', name: '7-P0519 - [ENERGLOBAL] Oleogasoducto de la Macro' },
  { id: '8', name: '8-FIELDWOOD' },
  { id: '9', name: '9-P0504 - [PROYECTA] TULA' },
  { id: '10', name: '10-P0505 - [CH4] Supervisión Estado de Jalisco' },
  { id: '11', name: '11-SIGMA' },
  { id: '12', name: '12-SUPREME' },
  { id: '13', name: '13-Traspasos intercompañia' },
  { id: '14', name: '14-Prestamos' },
  { id: '15', name: '15-Airtificial Aportación a fondo perdido' },
  { id: '16', name: '16-Otros Productos Financieros' },
  { id: '17', name: '17-Inversiones' },
  { id: '18', name: '18-Venta de Activos' },
  { id: '19', name: '19-Nómina' },
  { id: '20', name: '20-Aguinaldo' },
  { id: '21', name: '21-Gratificacion FA' },
  { id: '22', name: '22-PTU Garantizada' },
  { id: '23', name: '23-Finiquitos' },
  { id: '24', name: '24-Seguros' },
  { id: '25', name: '25-Nómina generico' },
  { id: '26', name: '26-IMSS, RCV e INFONAVIT' },
  { id: '27', name: '27-Impuesto Sobre Remuneraciones' },
  { id: '28', name: '28-ISR Personas Morales' },
  { id: '29', name: '29-Impuesto al Valor Agregado' },
  { id: '30', name: '30-ISR Retenido' },
  { id: '31', name: '31-IVA Retenido' },
  { id: '32', name: '32-Otros impuestos federales' },
  { id: '33', name: '33-Materiales' },
  { id: '34', name: '34-Honorarios' },
  { id: '35', name: '35-Servicios Profesionales' },
  { id: '36', name: '36-Equipo De Transporte' },
  { id: '37', name: '37-Equipo De Topografia' },
  { id: '38', name: '38-Equipo Computo (Software)' },
  { id: '39', name: '39-Equipo Computo (Hardware)' },
  { id: '40', name: '40-Equipo De Radiocomunicacion' },
  { id: '41', name: '41-Otros Equipos' },
  { id: '42', name: '42-Software e intangibles' },
  { id: '43', name: '43-Gastos De Viaje' },
  { id: '44', name: '44-Mantenimiento Y Rentas' },
  { id: '45', name: '45-Servicios' },
  { id: '46', name: '46-Fletes y Acarreo' },
  { id: '47', name: '47-Gastos De Oficina' },
  { id: '48', name: '48-Capacitacion Y Adiestramiento' },
  { id: '49', name: '49-Seguridad E Higiene' },
  { id: '50', name: '50-Seguros' },
  { id: '51', name: '51-Fianzas' },
  { id: '52', name: '52-Retencion de Clientes' },
  { id: '53', name: '53-Atención a clientes' },
  { id: '54', name: '54-Gastos Varios' },
  { id: '55', name: '55-No Deducibles' },
  { id: '56', name: '56-Intereses' },
  { id: '57', name: '57-Comisiones y Situaciones Banca' },
  { id: '58', name: '58-amortizacion de prestamos' },
  { id: '59', name: '59-American Express Company mexic' },
  { id: '60', name: '60-Descuentos Sobre Compras' },
  { id: '61', name: '61-Otros Gastos Financieros' },
  { id: '62', name: '62-Activo fijo' },
  { id: '63', name: '63-Otros activos' },
  { id: '65', name: '65-ISR por pagar' },
  { id: '66', name: '66-IVA por pagar' },
  { id: '67', name: '67-Retenidos por pagar' },
  { id: '68', name: '68-IMSS, RCV e INFONAVIT por pagar' },
  { id: '69', name: '69-Impuesto Sobre Remuneraciones por pagar' },
  { id: '70', name: '70-Otros impuestos por pagar' },
  { id: '71', name: '71-AMEXCO PYPSA Cta. 51003' },
  { id: '72', name: '72-Carbures Europe, S.A (Suc)' },
  { id: '73', name: '73-Cruz Jimenez Barrientos' },
  { id: '74', name: '74-Fonacot' },
  { id: '75', name: '75-Gratificacion Garantizada' },
  { id: '76', name: '76-Gratificacion FA' },
  { id: '77', name: '77-KBR Monterrey SA de CV' },
  { id: '78', name: '78-Pacma (2%)' },
  { id: '79', name: '79-Reembolsos y gastos varios' },
  { id: '80', name: '80-Otros Acreedores por Pagar' },
  { id: '81', name: '81-Csipa, S.A de C.V' },
  { id: '82', name: '82-Consultores Externos Asociados' },
  { id: '83', name: '83-GRV Oil Services S.A. de C.V.' },
  { id: '84', name: '84-Procomar, S.A de C.V' },
  { id: '85', name: '85-RP Geotecnia Ingenieria SA CV' },
  { id: '86', name: '86-Garcia Aguirre Rosa Linda' },
  { id: '87', name: '87-Marroquin Moran Gonzalo Higini' },
  { id: '88', name: '88-Beltran Reyes Jose Luis' },
  { id: '89', name: '89-Csipa, S.A de C.V' },
  { id: '90', name: '90-Cuatro Networks, S R.L. C.V.' },
  { id: '91', name: '91-DNV GL Mexico, S.R.L. DE C.V.' },
  { id: '92', name: '92-ER&M Mexico, S.A. DE C.V.' },
  { id: '93', name: '93-Grupo Planex, S.A.de C.V.' },
  { id: '94', name: '94-Geotecnia Dis y Estudi Geodesa' },
  { id: '95', name: '95-Grupo COSESI, S.A. de C.V.' },
  { id: '96', name: '96-Ingenieria Orco, S.A. de C.V.' },
  { id: '97', name: '97-Ingenieria Romar, S.A. de C.V.' },
  { id: '98', name: '98-It Ingenieros, S.A. de C.V.' },
  { id: '99', name: '99-Infraestructura GC, S.A. de C' },
  { id: '100', name: '100-Ing y manto industrial, S.A. d' },
  { id: '101', name: '101-Jacobo Vargas Carlos Roberto' },
  { id: '102', name: '102-KBR BONOS' },
  { id: '103', name: '103-Oglar, S.A. de C.V.' },
  { id: '104', name: '104-Procomar, S.A de C.V' },
  { id: '105', name: '105-Petresol SA CV' },
  { id: '106', name: '106-Prodesam Consultores Ambiental' },
  { id: '107', name: '107-Peralta Mendez Antonio' },
  { id: '108', name: '108-Subcontratos Mexibus' },
  { id: '109', name: '109-Spetro, S.A. de C.V.' },
  { id: '110', name: '110-Tecnosolum Ingenieria y Ciment' },
  { id: '111', name: '111-Torres Merino Elsa Karina' },
  { id: '112', name: '112-Otros Subcontratos no enlistados' },
  { id: '113', name: '113-Alpars Mexico, S.A de C.V' },
  { id: '114', name: '114-AXA Seguros, S.A. de C.V.' },
  { id: '115', name: '115-Bbsred Corporativo, S.A de C.V' },
  { id: '116', name: '116-Bianciardi, Ramirez y Cristant' },
  { id: '117', name: '117-Cuerpo de Guardias de Segurida' },
  { id: '118', name: '118-Compucentro, S.A. de C.V.' },
  { id: '119', name: '119-DHL Express México, SA de CV' },
  { id: '120', name: '120-Diez de Bonilla, Kuri y Asocia' },
  { id: '121', name: '121-Federacion Obrera Nacionalista' },
  { id: '122', name: '122-Federacion Integral de Obreros' },
  { id: '123', name: '123-Gpo Inmo la Joya Zomeyucan SA' },
  { id: '124', name: '124-PYP Prestamo accionistas' },
  { id: '125', name: '125-Jacinto Cañete Rolloso' },
  { id: '126', name: '126-Lloyd\'S Register Quality Assur' },
  { id: '127', name: '127-Marte Autorentas, S.A. de C.V.' },
  { id: '128', name: '128-Mapfre Mexico, S.A.' },
  { id: '129', name: '129-Notaria 185 Naucalpan, S.C' },
  { id: '130', name: '130-Olea Abogados, S.C.' },
  { id: '131', name: '131-Radiomovil Dipsa S.A. de C.V.' },
  { id: '132', name: '132-Telefonos de Mexico SAB CV' },
  { id: '133', name: '133-Telefonia por cable SA de CV' },
  { id: '134', name: '134-Aseguradora Aserta, SA de CV' },
  { id: '135', name: '135-Iberian Values, S.L.' },
  { id: '136', name: '136-Zama Garza Antonio' },
  { id: '137', name: '137-Pesantez Samiento Henry' },
  { id: '138', name: '138-Otros Proveedores no enlistados' },
  { id: '139', name: '139-Veronico Antonio Daniel' },
  { id: '140', name: '140-Compañía Mueblera Excelencia Educativa, SA de CV' },
  { id: '141', name: '141-Larrea Estrada Carlos Manuel' },
  { id: '142', name: '142-Beltran Reyes Jose Luis' },
  { id: '143', name: '143-Desarrollo Administrativo y Em' },
  { id: '144', name: '144-Habide Construccion e Ingenier' },
  { id: '145', name: '145-Houtu SA de CV' },
  { id: '146', name: '146-Diseño consultoria mantenimiento y obra Ipmars sa' },
  { id: '147', name: '147-Corporativo sman, S.A. de C.V.' },
  { id: '148', name: '148-CH Construction & Engeneering' },
  { id: '149', name: '149-Diprasa desarrollos industriales Pragmaticos SA CV' },
  { id: '150', name: '150-Geotecnia Dis y Estudi Geodesa' },
  { id: '151', name: '151-Ingeniería, Arquitectura y Est' },
  { id: '152', name: '152-Grupo Especializado en Obras Marinas SA de CV' },
  { id: '153', name: '153-P0512 - [AEME] Ingeniería BS JUJO (Segunda Etapa)' },
  { id: '154', name: '154-P0515 - [PTI] Logistica Apoyo Técnico a Construcción' },
  { id: '155', name: '155-Orange Engineering And Consulting Services' },
  { id: '156', name: '156-Nomarna Contrucciones E Ingenieria Sa De' },
  { id: '157', name: '157-Epesa Especialistas En Petroleo Y Energia Sa De Cv' },
  { id: '158', name: '158-Otros productos' },
  { id: '159', name: '159-Erea Servicios Integrales De Ingenieria' },
  { id: '160', name: '160-Grupo Gixtoh Ingenieria Y Medio Ambiente' },
  { id: '161', name: '161-Fuego y Gas SA de CV' },
  { id: '162', name: '162-Construagregados Hopelchen SA' },
  { id: '163', name: '163-Felix Hernandez Jose Lourdes' },
  { id: '164', name: '164-Inconyma' },
  { id: '165', name: '165-Administracion de riesgos industriales' },
  { id: '166', name: '166-Firla Constructor Y Edificaciones Sa' },
  { id: '167', name: '167-Bohrim Bim Lean Quality Sa De Cv' },
  { id: '168', name: '168-Juan Jose Jimenez Presenda' },
  { id: '169', name: '169-Valencia Consultores Ambientales SA' },
  { id: '170', name: '170-Inmoviliaria Aicm Sa De Cv' },
  { id: '172', name: '172-P0517 - [PEP] Servicios de ingeniería Marina y Costera' },
  { id: '173', name: '173-P0518 - [CH4] Gasoducto de los Altos' },
  { id: '174', name: '174-P0513 - [GCI] WBS 850-855-860' },
  { id: '175', name: '175-P0514 - [PTI] Mebi-meti Refineria Olmeca' },
  { id: '176', name: '176-Asesoria En Seguridad Industrial Sc' },
  { id: '177', name: '177-Corporativo Comercial Jasot S De RI De C' },
  { id: '178', name: '178-P0520 - [ICA] Energica Tenedora De Mexico' },
  { id: '179', name: '179-P0521 - [TRIFERTITAM]' },
  { id: '180', name: '180-P0524 - [CH4] Gasoducto los altos 2' },
  { id: '181', name: '181-Consultoria Proyectos Ingenieria Y Const' },
  { id: '182', name: '182-P0503 - [PROYECTA]' },
  { id: '183', name: '183-P0522 - [ICA]' },
  { id: '184', name: '184-P0525 - [FCC]' },
  { id: '185', name: '185-PTM Oil Services S de RL de CV' },
  { id: '186', name: '186-P0531 - CH4 Ingenieria Del Proyecto Arandas Etapa 1' },
  { id: '187', name: '187-P0532 - CH4 Supervision Epc Distribucion De Gas Natural Arandas-1, Jalisco' },
  { id: '188', name: '188-Luxia Energy Sa De Cv' },
  { id: '189', name: '189- Ikaloilmx Integrity Services Sa De Cv' },
  { id: '190', name: '190-0528 CME Oil & Gas' }
];

export const INITIAL_DEBIT_CARDS: DebitCard[] = [
    { id: '1', cardNumber: '**** 1234', assignedTo: 'Juan Perez' },
    { id: '2', cardNumber: '**** 5678', assignedTo: 'Maria Garcia' },
];

export const MOCK_TRANSACTIONS: Transaction[] = [];

export const TRANSACTION_HEADERS = ['BANCO', 'GUIA', 'FECHA', 'DESCRIPCION', 'IMPORTE MN', 'IMPORTE ME', 'TIPO', 'Asignado'];
export const SCHEDULED_PAYMENT_HEADERS = ['Resp', 'Proveedor', 'Concepto', 'M.E.', 'TC', 'Importe', 'Fecha'];